### ISSUE TITLE
How did you get the ground truth evidence set?

### ISSUE THREAD

**Issue by p-null** [UKPLab/fever-2018-team-athene#10]
Hi, I am reading your code to find how do you get the positive sentences and negative sentences.
I find `if doc_line[2] == evidence[3]`  at line 87 in `data.py` is the clause to determine whether a sentence in a retrived document is a ground truth sentence.  
But how did you get the ground truth evidence set? 
Thanks anyone who answer my question in advance.

**Comment by daniilsorokin** [comment]
Hi,

the Fever sharedtask data set that we use here contain the id of the document and the sentence id  for each evidence. See "Data Format" here: http://fever.ai/2018/task.html
The sentence id is just a sequential number of the sentences in the document. Hence when we retrieve the sentences we can just compare the sentence number to the current evidence number. 

The doc_lines is a list of tuples of the form (line: str, document_id:str, sentence_id: int). See the method here:
https://github.com/UKPLab/fever-2018-team-athene/blob/730e4055899680c2ce5d5be1881e36913041d490/src/athene/retrieval/sentences/data_processing/data.py#L92

I hope it helps,
Daniil

**Comment by p-null** [comment]
Got it. 
Thank you very much for answering!
