### ISSUE TITLE
Using pre-trained models

### ISSUE THREAD

**Issue by j6mes** [UKPLab/fever-2018-team-athene#2]
Hi, 

@hanselowski has shared some pretrained model files. I've got one zip for the sentence selection module and one zip for the claim validation module which have tensorflow checkpoints in them. 

What's the best way to use these within the context of running the full pipeline without having to train a new model? Should I extract both of these into the cpkt_folder specified in the json file? `"ckpt_folder": "model/no_attention_glove/checkpoints",` and just comment out the training lines in the pipeline.py file? Or is the a better way?

**Comment by hanselowski** [comment]
We are currently working on the scripts to run the pretrained models. There will be an update on the issue.

**Comment by littsler** [comment]
Hi @j6mes ,

the pipeline is updated. You can now predict the datasets with the pre-trained models by following the instruction.

**Comment by hanselowski** [comment]
We consider the issue to be closed

**Comment by j6mes** [comment]
Hi @hanselowski I can confirm this new pipeline script works well. Thank you for adding the functionality. I do see that the sentence-level preprocessing takes a couple of hours on my machine. Are pretrained models available for this too?

**Comment by hanselowski** [comment]
Hi,
We don't have a model for document retrieval, since we are using the media
wiki api and a bunch of tricks. However, the retrieved documents are
already stored in a file so you dont have to run the model again.
