### ISSUE TITLE
MLP neurons

### ISSUE THREAD

**Issue by ASoleimaniB** [UKPLab/fever-2018-team-athene#4]
I guess you wanted to have 900, 550, and 180 neurons for mlp units but below it seems that you are using 180,900,550. Am I right?
Since self.lstm_layers is assigned 1 from the Config file.

https://github.com/UKPLab/fever-2018-team-athene/blob/a3e8c857bf4107e960da2e9d652ea4d4fbfa02c7/src/athene/rte/deep_models/ESIM_for_ensemble.py#L362

**Comment by littsler** [comment]
Hi @ASoleimaniB Yes this is a bug. Thanks for reviewing the code so detailed. The funny thing is that our pre-trained model was then trained with the parameters 180,900.550. So I keep this set of parameters after fixing this bug, so that the pre-trained model can still be used.
